name: Tests
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      name: deploy secrets

    strategy:
      # 여러 개의 노드 버전으로 각각 다른 job들을 만들어냄
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install
      - run: yarn ci

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Compress the files
        run: zip -qq -r ./$GITHUB_SHA.zip .

      - run: echo $GITHUB_REPOSITORY

      - name: Upload to S3
        run: aws s3 cp --region $AWS_REGION ./$GITHUB_SHA.zip s3://only-deploy-test-bucket/$GITHUB_REPOSITORY/$GITHUB_SHA.zip

      - name: Create new Deployment
        run: aws deploy create-deployment --application-name deploy-test --deployment-config-name CodeDeployDefault.AllAtATime --deployment-group-name deploy-group --s3-location bucket=only-deploy-test-bucket,bundleType=zip,key=$GITHUB_REPOSITORY/$GITHUB_SHA.zip
